// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    token_hash,
    expires_at,
    user_agent,
    ip
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    user_id,
    expires_at,
    created_at
`

type CreateSessionParams struct {
	UserID    int64
	TokenHash []byte
	ExpiresAt time.Time
	UserAgent *string
	Ip        *netip.Addr
}

type CreateSessionRow struct {
	ID        int64
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

// token_hash is supplied by the caller, already hashed. The plaintext token
// never reaches the database.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    username,
    password_hash,
    role,
    display_name
) VALUES (
    $1, $2, $3, $4
)
RETURNING
    id,
    username,
    role,
    display_name,
    created_at,
    updated_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
	Role         string
	DisplayName  *string
}

type CreateUserRow struct {
	ID          int64
	Username    string
	Role        string
	DisplayName *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Queries for the owner account and its sessions.
//
// These return database facts and nothing more. Whether a session has expired
// is a decision, so it is not encoded here: GetSessionByHash returns an expired
// row and lets the service layer rule on it. A SQL-level expiry filter would
// make "expired" and "no such session" indistinguishable to the caller.
// password_hash is written but not returned. A hash has no use above the
// repository except during a login comparison, which GetUserByUsername serves.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.DisplayName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= now()
`

// Periodic cleanup, driven by a CLI command. Returns the number of rows removed
// so the command can report it.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

// Logout. Deleting a missing row is not an error here; the caller's goal is
// that the session no longer exists, and it does not.
func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByHash = `-- name: DeleteSessionByHash :exec
DELETE FROM sessions
WHERE token_hash = $1
`

// Logout. The request carries only the cookie, so deleting by hash ends the
// session in one round trip instead of a lookup followed by a delete by id.
// DeleteSession stays for callers that already hold the id.
func (q *Queries) DeleteSessionByHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByHash, tokenHash)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT
    s.id,
    s.user_id,
    s.token_hash,
    s.expires_at,
    s.created_at,
    s.user_agent,
    s.ip,
    u.id           AS user_id_ref,
    u.username     AS user_username,
    u.role         AS user_role,
    u.display_name AS user_display_name,
    u.created_at   AS user_created_at,
    u.updated_at   AS user_updated_at
FROM sessions s
INNER JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionByHashRow struct {
	ID              int64
	UserID          int64
	TokenHash       []byte
	ExpiresAt       time.Time
	CreatedAt       time.Time
	UserAgent       *string
	Ip              *netip.Addr
	UserIDRef       int64
	UserUsername    string
	UserRole        string
	UserDisplayName *string
	UserCreatedAt   time.Time
	UserUpdatedAt   time.Time
}

// The authentication lookup. One round trip returns the session and its user,
// because this runs on every protected request and a second query would double
// that cost.
//
// Deliberately no "AND expires_at > now()". The row comes back whatever its
// expiry, and the service decides. That keeps two different outcomes apart:
// an unknown token and a known but expired one.
func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash []byte) (GetSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, tokenHash)
	var i GetSessionByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.Ip,
		&i.UserIDRef,
		&i.UserUsername,
		&i.UserRole,
		&i.UserDisplayName,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    username,
    role,
    display_name,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          int64
	Username    string
	Role        string
	DisplayName *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id,
    username,
    password_hash,
    role,
    display_name,
    created_at,
    updated_at
FROM users
WHERE username = $1
`

// The login lookup, and the only query that exposes password_hash.
//
// No lower() on either side: username is citext, so the comparison is already
// case-insensitive. Wrapping the column in lower() would also make the query
// unable to use the unique index.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET expires_at = $2
WHERE id = $1
`

type TouchSessionParams struct {
	ID        int64
	ExpiresAt time.Time
}

// Sliding renewal. The service calls this only when a session is past the
// halfway point of its lifetime, so an active session is not one write per
// request.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}
