// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package sqlcgen

import (
	"context"
	"time"
)

const categorySlugExists = `-- name: CategorySlugExists :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE world = $1
      AND slug = $2
)
`

type CategorySlugExistsParams struct {
	World string
	Slug  string
}

func (q *Queries) CategorySlugExists(ctx context.Context, arg CategorySlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, categorySlugExists, arg.World, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categorySlugExistsExcluding = `-- name: CategorySlugExistsExcluding :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE world = $1
      AND slug = $2
      AND id <> $3
)
`

type CategorySlugExistsExcludingParams struct {
	World      string
	Slug       string
	ExcludedID int64
}

func (q *Queries) CategorySlugExistsExcluding(ctx context.Context, arg CategorySlugExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, categorySlugExistsExcluding, arg.World, arg.Slug, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    world,
    name,
    slug,
    description,
    sort_order
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    world,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
`

type CreateCategoryParams struct {
	World       string
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
}

type CreateCategoryRow struct {
	ID          int64
	World       string
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.World,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
	)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.World,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM categories
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteCategory, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
    id,
    world,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
FROM categories
WHERE id = $1
`

type GetCategoryByIDRow struct {
	ID          int64
	World       string
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (GetCategoryByIDRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.World,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT
    id,
    world,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
FROM categories
WHERE world = $1
  AND slug = $2
`

type GetCategoryBySlugParams struct {
	World string
	Slug  string
}

type GetCategoryBySlugRow struct {
	ID          int64
	World       string
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (GetCategoryBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, arg.World, arg.Slug)
	var i GetCategoryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.World,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    id,
    world,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
FROM categories
WHERE world = $1
ORDER BY sort_order, id
`

type ListCategoriesRow struct {
	ID          int64
	World       string
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListCategories(ctx context.Context, world string) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, world)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.World,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithCounts = `-- name: ListCategoriesWithCounts :many
SELECT
    c.id,
    c.world,
    c.name,
    c.slug,
    c.description,
    c.sort_order,
    c.created_at,
    c.updated_at,
    count(e.id) AS entry_count
FROM categories c
LEFT JOIN entries e
    ON e.category_id = c.id
   AND e.world = c.world
   AND e.deleted_at IS NULL
   AND e.status = 'published'
   AND e.visibility = 'public'
WHERE c.world = $1
GROUP BY c.id
ORDER BY c.sort_order, c.id
`

type ListCategoriesWithCountsRow struct {
	ID          int64
	World       string
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	EntryCount  int64
}

func (q *Queries) ListCategoriesWithCounts(ctx context.Context, world string) ([]ListCategoriesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesWithCounts, world)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesWithCountsRow{}
	for rows.Next() {
		var i ListCategoriesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.World,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = CASE WHEN $1::boolean
                THEN $2::varchar ELSE name END,
    slug = CASE WHEN $3::boolean
                THEN $4::varchar ELSE slug END,
    description = CASE WHEN $5::boolean
                       THEN $6::text ELSE description END,
    sort_order = CASE WHEN $7::boolean
                      THEN $8::int ELSE sort_order END
WHERE id = $9
RETURNING
    id,
    world,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
`

type UpdateCategoryParams struct {
	SetName        bool
	Name           string
	SetSlug        bool
	Slug           string
	SetDescription bool
	Description    *string
	SetSortOrder   bool
	SortOrder      int32
	ID             int64
}

type UpdateCategoryRow struct {
	ID          int64
	World       string
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.SetName,
		arg.Name,
		arg.SetSlug,
		arg.Slug,
		arg.SetDescription,
		arg.Description,
		arg.SetSortOrder,
		arg.SortOrder,
		arg.ID,
	)
	var i UpdateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.World,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
