// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package sqlcgen

import (
	"context"
	"time"
)

const categorySlugExists = `-- name: CategorySlugExists :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE slug = $1
)
`

// Whether any category already holds this slug.
//
// Asked before an insert so the caller gets a conflict naming the field rather
// than a constraint violation. It does not replace categories_slug_key: two
// concurrent creates can both read false, and the constraint is what settles it.
func (q *Queries) CategorySlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, categorySlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categorySlugExistsExcluding = `-- name: CategorySlugExistsExcluding :one
SELECT EXISTS (
    SELECT 1
    FROM categories
    WHERE slug = $1
      AND id <> $2
)
`

type CategorySlugExistsExcludingParams struct {
	Slug       string
	ExcludedID int64
}

// Whether a category other than this one holds the slug.
//
// The exclusion is what lets an edit form submit a category's own slug back
// unchanged without being refused as a conflict with itself.
func (q *Queries) CategorySlugExistsExcluding(ctx context.Context, arg CategorySlugExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, categorySlugExistsExcluding, arg.Slug, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (
    name,
    slug,
    description,
    sort_order
) VALUES (
    $1, $2, $3, $4
)
RETURNING
    id,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
`

type CreateCategoryParams struct {
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
}

// Queries for categories.
//
// Unlike entries, there is no visibility rule to enforce here and no soft
// delete to filter on. A category is a name, a slug and a sort order; it carries
// no content of its own, so the reads are the same set of rows for everyone and
// a delete is a delete.
//
// What is not the same for everyone is the count attached to each category. The
// public list counts only entries a public reader could reach, so the number
// beside a category matches what opening it will show. ListCategoriesWithCounts
// carries that filter; ListCategories has no count at all.
// Insert one category.
//
// sort_order arrives from the caller rather than defaulting here, so that the
// domain owns what "unspecified" means.
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :one
DELETE FROM categories
WHERE id = $1
RETURNING id
`

// Delete one category, returning its id so the caller can tell a hit from a miss.
//
// A physical delete, unlike an entry. A category is a name and a slug, so
// recreating one costs nothing, and a deleted_at here would add a condition to
// every read of a table that has no other reason to need one.
//
// Entries referencing it are not touched by this statement. The foreign key is
// ON DELETE SET NULL, so they become uncategorised. That makes this delete
// succeed quietly even when the category is in use: nothing afterwards records
// which category those rows pointed at.
func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteCategory, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
    id,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
FROM categories
WHERE id = $1
`

// Read one category by id. Used after a write and by the admin edit form.
func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT
    id,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
FROM categories
WHERE slug = $1
`

// Read one category by slug.
//
// This is how a category page resolves its URL segment, and how a list request
// filtered by category turns ?category=travel into an id. Resolving first means
// an unknown slug is a 404 rather than an empty list, which are different
// answers: one says the URL is wrong, the other says the category is empty.
func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    id,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
FROM categories
ORDER BY sort_order, id
`

// Every category, in display order.
//
// sort_order first, then id as the tie-break so that categories sharing a
// sort_order have a stable order rather than whatever the planner returns. No
// pagination: this is a navigation structure, and one that needs paging is one
// nobody can navigate.
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithCounts = `-- name: ListCategoriesWithCounts :many
SELECT
    c.id,
    c.name,
    c.slug,
    c.description,
    c.sort_order,
    c.created_at,
    c.updated_at,
    count(e.id) AS entry_count
FROM categories c
LEFT JOIN entries e
    ON e.category_id = c.id
   AND e.deleted_at IS NULL
   AND e.status = 'published'
   AND e.visibility = 'public'
GROUP BY c.id
ORDER BY c.sort_order, c.id
`

type ListCategoriesWithCountsRow struct {
	ID          int64
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	EntryCount  int64
}

// Every category with the number of entries a public reader can see in it.
//
// LEFT JOIN, not an inner one, so a category with nothing in it still appears
// with a count of zero. Whether to show an empty category is a display decision,
// and hiding it here would leave the frontend unable to make it.
//
// The count conditions sit in the JOIN clause rather than in a WHERE. In a WHERE
// they would discard the whole category row when no entry matched, turning the
// LEFT JOIN back into an inner one.
//
// Same three conditions as the public entry reads: not deleted, published,
// public. An unlisted entry is deliberately not counted, since it is absent from
// the list the count describes.
func (q *Queries) ListCategoriesWithCounts(ctx context.Context) ([]ListCategoriesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesWithCountsRow{}
	for rows.Next() {
		var i ListCategoriesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
    name = CASE WHEN $1::boolean
                THEN $2::varchar ELSE name END,
    slug = CASE WHEN $3::boolean
                THEN $4::varchar ELSE slug END,
    description = CASE WHEN $5::boolean
                       THEN $6::text ELSE description END,
    sort_order = CASE WHEN $7::boolean
                      THEN $8::int ELSE sort_order END
WHERE id = $9
RETURNING
    id,
    name,
    slug,
    description,
    sort_order,
    created_at,
    updated_at
`

type UpdateCategoryParams struct {
	SetName        bool
	Name           string
	SetSlug        bool
	Slug           string
	SetDescription bool
	Description    *string
	SetSortOrder   bool
	SortOrder      int32
	ID             int64
}

// Apply a partial update to one category.
//
// The same paired-flag shape as UpdateEntry, and for the same reason: description
// is nullable, so "clear the description" and "leave it alone" both arrive as
// NULL under COALESCE and would become one statement.
//
// updated_at is left to the categories_set_updated_at trigger.
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.SetName,
		arg.Name,
		arg.SetSlug,
		arg.Slug,
		arg.SetDescription,
		arg.Description,
		arg.SetSortOrder,
		arg.SortOrder,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
