// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const archiveEntry = `-- name: ArchiveEntry :one
UPDATE entries
SET status = 'archived'
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    author_id,
    category_id,
    type,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type ArchiveEntryRow struct {
	ID          int64
	AuthorID    int64
	CategoryID  *int64
	Type        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Retire one entry: off the site, but not deleted.
//
// Distinct from both of the above. A draft is unfinished and an archived entry is
// finished and withdrawn, and the difference matters in the admin list: drafts are
// a work queue, archived entries are not. Distinct from a soft delete too, since
// this one is still listed and still editable.
//
// published_at survives here for the same reason it survives unpublishing.
func (q *Queries) ArchiveEntry(ctx context.Context, id int64) (ArchiveEntryRow, error) {
	row := q.db.QueryRow(ctx, archiveEntry, id)
	var i ArchiveEntryRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAdminEntries = `-- name: CountAdminEntries :one
SELECT count(*)
FROM entries
WHERE deleted_at IS NULL
  AND ($1::varchar IS NULL OR status = $1::varchar)
`

// The total for the admin list, under the same filter.
func (q *Queries) CountAdminEntries(ctx context.Context, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminEntries, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicEntries = `-- name: CountPublicEntries :one
SELECT count(*)
FROM entries
WHERE deleted_at IS NULL
  AND status = 'published'
  AND visibility = 'public'
  AND ($1::bigint IS NULL
       OR category_id = $1::bigint)
`

// The total for the pagination block, under the same filter as the list.
//
// A separate statement rather than a window function on the list query. With
// count(*) OVER () the total arrives only when at least one row does, so the
// last page plus one would report a total of zero.
//
// No join here: the count needs no category name, only the same filter.
func (q *Queries) CountPublicEntries(ctx context.Context, categoryID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicEntries, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntry = `-- name: CreateEntry :one

INSERT INTO entries (
    author_id,
    category_id,
    type,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING
    id,
    author_id,
    category_id,
    type,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type CreateEntryParams struct {
	AuthorID    int64
	CategoryID  *int64
	Type        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
}

type CreateEntryRow struct {
	ID          int64
	AuthorID    int64
	CategoryID  *int64
	Type        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Queries for entries.
//
// The visibility rule is in SQL, not in Go. Every public read carries
// "deleted_at IS NULL AND status = 'published' AND visibility = 'public'" as
// part of the statement, so a caller cannot reach an unpublished row by
// forgetting a filter. The three conditions also match the partial index
// idx_entries_public_feed exactly, so the planner uses it for these queries.
//
// The admin queries, which do see drafts, are separate statements rather than a
// flag on these. A boolean that switches the visibility filter on and off is one
// wrong argument away from publishing every draft. They are named Admin* and
// appear at the end of this file; no query serves both audiences.
//
// GetLinkEntryBySlug is the one public read that accepts 'unlisted' as well as
// 'public'. It is a separate statement for the reason above, not a parameter on
// GetPublicEntryBySlug: an entry reachable by link must stay out of the lists,
// and a shared query with a flag would make that depend on the argument.
//
// The reads LEFT JOIN categories to carry the category name and slug, so one
// response needs one query. The writes cannot: RETURNING sees only the row being
// written, so they hand back category_id alone and a caller that needs the name
// reads the entry back. That asymmetry is in the generated types too, which is
// why the domain has two conversion paths.
// Insert one entry.
//
// published_at is a parameter rather than a now() call, because "first
// published" is a decision the service makes: it is set when an entry is created
// as published, and never rewritten afterwards. Passing now() here would move it
// on every write.
//
// word_count likewise arrives computed. Counting words in SQL would tie the
// definition of a word to Postgres' text functions, and the domain owns that
// rule.
// category_id is nullable and NULL means uncategorised, which is a normal state
// rather than missing data. The foreign key refuses an id no category holds, so a
// typo here is a constraint violation the repository translates, not a row
// pointing at nothing.
func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (CreateEntryRow, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.AuthorID,
		arg.CategoryID,
		arg.Type,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.ContentMd,
		arg.CoverUrl,
		arg.Status,
		arg.Visibility,
		arg.Meta,
		arg.WordCount,
		arg.HappenedAt,
		arg.PublishedAt,
	)
	var i CreateEntryRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const entrySlugExists = `-- name: EntrySlugExists :one
SELECT EXISTS (
    SELECT 1
    FROM entries
    WHERE slug = $1
      AND deleted_at IS NULL
)
`

// Whether a live entry already holds this slug.
//
// Used to answer a conflict before attempting the insert, so the caller gets a
// clear 409 rather than a constraint violation. It does not replace the unique
// index: two concurrent creates can both see false here, and the index is what
// settles it. The repository translates that violation to the same conflict.
//
// Matches uk_entries_slug: deleted rows do not hold their slug.
func (q *Queries) EntrySlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, entrySlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const entrySlugExistsExcluding = `-- name: EntrySlugExistsExcluding :one
SELECT EXISTS (
    SELECT 1
    FROM entries
    WHERE slug = $1
      AND id <> $2
      AND deleted_at IS NULL
)
`

type EntrySlugExistsExcludingParams struct {
	Slug       string
	ExcludedID int64
}

// Whether a live entry other than this one holds the slug.
//
// The exclusion is what makes a no-op slug change work: submitting an entry's own
// slug back must not be refused as a conflict with itself.
func (q *Queries) EntrySlugExistsExcluding(ctx context.Context, arg EntrySlugExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, entrySlugExistsExcluding, arg.Slug, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAdminEntryByID = `-- name: GetAdminEntryByID :one
SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.type,
    e.title,
    e.slug,
    e.summary,
    e.content_md,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.id = $1
  AND e.deleted_at IS NULL
`

type GetAdminEntryByIDRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	Type         string
	Title        string
	Slug         string
	Summary      *string
	ContentMd    string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// The admin detail read, addressed by id rather than slug.
//
// By id because a draft is edited before its slug is settled, and because a slug
// may change during editing while the thing being edited does not.
func (q *Queries) GetAdminEntryByID(ctx context.Context, id int64) (GetAdminEntryByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminEntryByID, id)
	var i GetAdminEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkEntryBySlug = `-- name: GetLinkEntryBySlug :one
SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.type,
    e.title,
    e.slug,
    e.summary,
    e.content_md,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.slug = $1
  AND e.deleted_at IS NULL
  AND e.status = 'published'
  AND e.visibility IN ('public', 'unlisted')
`

type GetLinkEntryBySlugRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	Type         string
	Title        string
	Slug         string
	Summary      *string
	ContentMd    string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// The detail read behind a shared link: public or unlisted.
//
// This is what GET /entries/:slug uses, so that an unlisted entry can be opened
// by anyone holding its URL while staying out of every list, count and sitemap.
// The lists above are unchanged and still say visibility = 'public'.
//
// Note what unlisted does and does not buy. A slug is human readable and
// guessable, so this is "not advertised", not access control: it keeps an entry
// off the front page and out of search engines, and that is all. An entry that
// must not be readable by a stranger is 'private', which no public statement
// accepts.
func (q *Queries) GetLinkEntryBySlug(ctx context.Context, slug string) (GetLinkEntryBySlugRow, error) {
	row := q.db.QueryRow(ctx, getLinkEntryBySlug, slug)
	var i GetLinkEntryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicEntryBySlug = `-- name: GetPublicEntryBySlug :one
SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.type,
    e.title,
    e.slug,
    e.summary,
    e.content_md,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.slug = $1
  AND e.deleted_at IS NULL
  AND e.status = 'published'
  AND e.visibility = 'public'
`

type GetPublicEntryBySlugRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	Type         string
	Title        string
	Slug         string
	Summary      *string
	ContentMd    string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// The strictly public detail read, addressed by slug.
//
// Returns content_md: the detail endpoints are the ones that need the body.
//
// Kept alongside GetLinkEntryBySlug rather than replaced by it. This one is what
// a sitemap generator or a feed builder should ask, because those enumerate what
// is meant to be found, and an unlisted entry is not.
func (q *Queries) GetPublicEntryBySlug(ctx context.Context, slug string) (GetPublicEntryBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicEntryBySlug, slug)
	var i GetPublicEntryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminEntries = `-- name: ListAdminEntries :many

SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.type,
    e.title,
    e.slug,
    e.summary,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.deleted_at IS NULL
  AND ($1::varchar IS NULL OR e.status = $1::varchar)
ORDER BY e.updated_at DESC, e.id DESC
LIMIT $3 OFFSET $2
`

type ListAdminEntriesParams struct {
	Status *string
	Offset int32
	Limit  int32
}

type ListAdminEntriesRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	Type         string
	Title        string
	Slug         string
	Summary      *string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// The admin reads.
//
// Separate statements from the public ones above, not the same queries with the
// filter parameterised. These see every status and every visibility, and the only
// thing keeping a draft off the front page is that the public queries cannot
// express this. A shared query with a boolean would put that guarantee in the
// hands of whoever passes the argument.
//
// Soft deleted rows are excluded here too. There is no endpoint that shows them
// and no restore, so a deleted entry is out of reach from every route.
// The admin list: every status, ordered by last edit.
//
// updated_at DESC, not happened_at: this list is a work queue, so what was
// touched last belongs at the top. The public list answers a different question
// and sorts differently. Matches idx_entries_admin.
//
// The status filter is a nullable argument: NULL means every status. That is not
// the same hazard as parameterising the visibility filter, because no draft is
// being kept from anyone here. Every row this statement can return is already
// visible to the caller.
//
// No content_md, for the same reason the public list omits it.
func (q *Queries) ListAdminEntries(ctx context.Context, arg ListAdminEntriesParams) ([]ListAdminEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAdminEntries, arg.Status, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminEntriesRow{}
	for rows.Next() {
		var i ListAdminEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.Type,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.CoverUrl,
			&i.Status,
			&i.Visibility,
			&i.Meta,
			&i.WordCount,
			&i.HappenedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicEntries = `-- name: ListPublicEntries :many
SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.type,
    e.title,
    e.slug,
    e.summary,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.deleted_at IS NULL
  AND e.status = 'published'
  AND e.visibility = 'public'
  AND ($1::bigint IS NULL
       OR e.category_id = $1::bigint)
ORDER BY e.happened_at DESC NULLS LAST, e.id DESC
LIMIT $3 OFFSET $2
`

type ListPublicEntriesParams struct {
	CategoryID *int64
	Offset     int32
	Limit      int32
}

type ListPublicEntriesRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	Type         string
	Title        string
	Slug         string
	Summary      *string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// The public list, newest happening first.
//
// No content_md in the column list. A list of twenty entries carrying twenty
// Markdown bodies is a response tens of times larger than the page needs, and
// nothing on a list view renders the body.
//
// Ordered by happened_at, not created_at: the timeline records when things
// happened, not when they were typed. NULLS LAST keeps entries with no recorded
// date at the end instead of at the top, since DESC sorts NULL first by default.
// id DESC breaks ties, which is what stops a row appearing on two pages when
// several share a happened_at.
// The category filter is a nullable id: NULL means every category. The caller
// passes an id, not a slug, because the service resolves the slug first — that
// way an unknown category is a 404 saying the URL is wrong, rather than an empty
// list saying the category has nothing in it.
//
// One thing this shape cannot express is "only the uncategorised ones", since
// that would need a third state alongside "this category" and "all". No endpoint
// asks for it: uncategorised is not a navigable page, having neither a name nor a
// slug. Adding it later means a separate statement, not another argument.
func (q *Queries) ListPublicEntries(ctx context.Context, arg ListPublicEntriesParams) ([]ListPublicEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPublicEntries, arg.CategoryID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicEntriesRow{}
	for rows.Next() {
		var i ListPublicEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.Type,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.CoverUrl,
			&i.Status,
			&i.Visibility,
			&i.Meta,
			&i.WordCount,
			&i.HappenedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishEntry = `-- name: PublishEntry :one
UPDATE entries
SET
    status = 'published',
    published_at = COALESCE(published_at, $1)
WHERE id = $2
  AND deleted_at IS NULL
RETURNING
    id,
    author_id,
    category_id,
    type,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type PublishEntryParams struct {
	PublishedAt *time.Time
	ID          int64
}

type PublishEntryRow struct {
	ID          int64
	AuthorID    int64
	CategoryID  *int64
	Type        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Publish one entry, stamping published_at only if it has never been set.
//
// Both changes are in one statement because entries_published_at_check refuses a
// row with status 'published' and a NULL published_at. Two statements would leave
// the row invalid between them, and the constraint would reject the first.
//
// COALESCE is the whole rule: an entry published, withdrawn and published again
// keeps its original date, so fixing a typo years later does not move a
// three-year-old entry to the top of the feed.
func (q *Queries) PublishEntry(ctx context.Context, arg PublishEntryParams) (PublishEntryRow, error) {
	row := q.db.QueryRow(ctx, publishEntry, arg.PublishedAt, arg.ID)
	var i PublishEntryRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteEntry = `-- name: SoftDeleteEntry :one
UPDATE entries
SET deleted_at = $1
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteEntryParams struct {
	DeletedAt *time.Time
	ID        int64
}

// Mark one entry deleted, returning its id so the caller can tell a hit from a
// miss.
//
// deleted_at IS NULL in the WHERE makes this report no row on a second call
// rather than moving the timestamp. The first delete is the one that happened,
// and a repeat must not rewrite when.
//
// The row stays. Content is not regenerable, and every read filters on
// deleted_at, so the row is unreachable without being gone. Note that the slug
// is released: uk_entries_slug is partial on deleted_at IS NULL, so a later
// entry may take it.
func (q *Queries) SoftDeleteEntry(ctx context.Context, arg SoftDeleteEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteEntry, arg.DeletedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const unpublishEntry = `-- name: UnpublishEntry :one
UPDATE entries
SET status = 'draft'
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
    id,
    author_id,
    category_id,
    type,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type UnpublishEntryRow struct {
	ID          int64
	AuthorID    int64
	CategoryID  *int64
	Type        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Return one entry to draft.
//
// published_at is deliberately untouched: it records the first publication, which
// is a fact that withdrawing does not undo. Clearing it would make a
// re-publication look like a first one and move the entry to the top of the feed.
func (q *Queries) UnpublishEntry(ctx context.Context, id int64) (UnpublishEntryRow, error) {
	row := q.db.QueryRow(ctx, unpublishEntry, id)
	var i UnpublishEntryRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET
    type = CASE WHEN $1::boolean
                THEN $2::varchar ELSE type END,
    title = CASE WHEN $3::boolean
                 THEN $4::varchar ELSE title END,
    slug = CASE WHEN $5::boolean
                THEN $6::varchar ELSE slug END,
    summary = CASE WHEN $7::boolean
                   THEN $8::text ELSE summary END,
    content_md = CASE WHEN $9::boolean
                      THEN $10::text ELSE content_md END,
    word_count = CASE WHEN $9::boolean
                      THEN $11::int ELSE word_count END,
    cover_url = CASE WHEN $12::boolean
                     THEN $13::text ELSE cover_url END,
    visibility = CASE WHEN $14::boolean
                      THEN $15::varchar ELSE visibility END,
    meta = CASE WHEN $16::boolean
                THEN $17::jsonb ELSE meta END,
    happened_at = CASE WHEN $18::boolean
                       THEN $19::timestamptz ELSE happened_at END,
    -- Clearing this one is what makes an entry uncategorised again: set_category_id
    -- true with a NULL value. Under COALESCE that would be indistinguishable from
    -- leaving the category as it is, which is the whole reason for the flags.
    category_id = CASE WHEN $20::boolean
                       THEN $21::bigint ELSE category_id END
WHERE id = $22
  AND deleted_at IS NULL
RETURNING
    id,
    author_id,
    category_id,
    type,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type UpdateEntryParams struct {
	SetType       bool
	Type          string
	SetTitle      bool
	Title         string
	SetSlug       bool
	Slug          string
	SetSummary    bool
	Summary       *string
	SetContentMd  bool
	ContentMd     string
	WordCount     int32
	SetCoverUrl   bool
	CoverUrl      *string
	SetVisibility bool
	Visibility    string
	SetMeta       bool
	Meta          json.RawMessage
	SetHappenedAt bool
	HappenedAt    *time.Time
	SetCategoryID bool
	CategoryID    *int64
	ID            int64
}

type UpdateEntryRow struct {
	ID          int64
	AuthorID    int64
	CategoryID  *int64
	Type        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Apply a partial update to one live entry.
//
// Every field is a pair: a boolean saying whether the caller asked for this
// field, and the value to write. The boolean is not redundant with a NULL value,
// and this is why COALESCE is not used here: summary, cover_url and happened_at
// are nullable, so "clear this field" and "leave this field alone" both arrive as
// NULL under COALESCE and become the same statement. With the flag, clearing a
// summary is set_summary = true and summary = NULL, which is distinct from
// set_summary = false.
//
// status is absent on purpose. Publishing carries the published_at rule, and
// PublishEntry below owns it; allowing status here would put that rule in two
// places, and the CHECK constraint would reject the write anyway once status
// became 'published' with a NULL published_at.
//
// word_count travels with content_md rather than being its own parameter: it is
// derived from the body, so accepting it separately would let the two disagree.
//
// updated_at is left to the entries_set_updated_at trigger from 000001.
func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (UpdateEntryRow, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.SetType,
		arg.Type,
		arg.SetTitle,
		arg.Title,
		arg.SetSlug,
		arg.Slug,
		arg.SetSummary,
		arg.Summary,
		arg.SetContentMd,
		arg.ContentMd,
		arg.WordCount,
		arg.SetCoverUrl,
		arg.CoverUrl,
		arg.SetVisibility,
		arg.Visibility,
		arg.SetMeta,
		arg.Meta,
		arg.SetHappenedAt,
		arg.HappenedAt,
		arg.SetCategoryID,
		arg.CategoryID,
		arg.ID,
	)
	var i UpdateEntryRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.Type,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
