// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entry.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const archiveEntry = `-- name: ArchiveEntry :one
UPDATE entries
SET
    revision = revision + 1,
    status = 'archived'
WHERE id = $1
  AND revision = $2
  AND deleted_at IS NULL
RETURNING
    id,
    revision,
    author_id,
    category_id,
    world,
    kind,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type ArchiveEntryParams struct {
	ID               int64
	ExpectedRevision int64
}

type ArchiveEntryRow struct {
	ID          int64
	Revision    int64
	AuthorID    int64
	CategoryID  *int64
	World       string
	Kind        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ArchiveEntry(ctx context.Context, arg ArchiveEntryParams) (ArchiveEntryRow, error) {
	row := q.db.QueryRow(ctx, archiveEntry, arg.ID, arg.ExpectedRevision)
	var i ArchiveEntryRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.AuthorID,
		&i.CategoryID,
		&i.World,
		&i.Kind,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAdminEntries = `-- name: CountAdminEntries :one
SELECT count(*)
FROM entries
WHERE deleted_at IS NULL
  AND ($1::varchar IS NULL OR world = $1::varchar)
  AND ($2::bigint IS NULL OR category_id = $2::bigint)
  AND ($3::varchar IS NULL OR status = $3::varchar)
  AND (
    $4::text IS NULL
    OR title ILIKE '%' || $4::text || '%'
    OR slug ILIKE '%' || $4::text || '%'
    OR COALESCE(summary, '') ILIKE '%' || $4::text || '%'
  )
`

type CountAdminEntriesParams struct {
	World      *string
	CategoryID *int64
	Status     *string
	Search     *string
}

func (q *Queries) CountAdminEntries(ctx context.Context, arg CountAdminEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminEntries,
		arg.World,
		arg.CategoryID,
		arg.Status,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicEntries = `-- name: CountPublicEntries :one
SELECT count(*)
FROM entries
WHERE world = $1
  AND deleted_at IS NULL
  AND status = 'published'
  AND visibility = 'public'
  AND ($2::bigint IS NULL
       OR category_id = $2::bigint)
`

type CountPublicEntriesParams struct {
	World      string
	CategoryID *int64
}

func (q *Queries) CountPublicEntries(ctx context.Context, arg CountPublicEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicEntries, arg.World, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    author_id,
    category_id,
    world,
    kind,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING
    id,
    revision,
    author_id,
    category_id,
    world,
    kind,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type CreateEntryParams struct {
	AuthorID    int64
	CategoryID  *int64
	World       string
	Kind        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
}

type CreateEntryRow struct {
	ID          int64
	Revision    int64
	AuthorID    int64
	CategoryID  *int64
	World       string
	Kind        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (CreateEntryRow, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.AuthorID,
		arg.CategoryID,
		arg.World,
		arg.Kind,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.ContentMd,
		arg.CoverUrl,
		arg.Status,
		arg.Visibility,
		arg.Meta,
		arg.WordCount,
		arg.HappenedAt,
		arg.PublishedAt,
	)
	var i CreateEntryRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.AuthorID,
		&i.CategoryID,
		&i.World,
		&i.Kind,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dashboardMetrics = `-- name: DashboardMetrics :one
SELECT
    count(*) AS total_entries,
    count(*) FILTER (WHERE status = 'published') AS published_entries,
    COALESCE(sum(word_count), 0)::bigint AS total_words
FROM entries
WHERE deleted_at IS NULL
`

type DashboardMetricsRow struct {
	TotalEntries     int64
	PublishedEntries int64
	TotalWords       int64
}

func (q *Queries) DashboardMetrics(ctx context.Context) (DashboardMetricsRow, error) {
	row := q.db.QueryRow(ctx, dashboardMetrics)
	var i DashboardMetricsRow
	err := row.Scan(&i.TotalEntries, &i.PublishedEntries, &i.TotalWords)
	return i, err
}

const entrySlugExists = `-- name: EntrySlugExists :one
SELECT EXISTS (
    SELECT 1
    FROM entries
    WHERE world = $1
      AND slug = $2
      AND deleted_at IS NULL
)
`

type EntrySlugExistsParams struct {
	World string
	Slug  string
}

func (q *Queries) EntrySlugExists(ctx context.Context, arg EntrySlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, entrySlugExists, arg.World, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const entrySlugExistsExcluding = `-- name: EntrySlugExistsExcluding :one
SELECT EXISTS (
    SELECT 1
    FROM entries
    WHERE world = $1
      AND slug = $2
      AND id <> $3
      AND deleted_at IS NULL
)
`

type EntrySlugExistsExcludingParams struct {
	World      string
	Slug       string
	ExcludedID int64
}

func (q *Queries) EntrySlugExistsExcluding(ctx context.Context, arg EntrySlugExistsExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, entrySlugExistsExcluding, arg.World, arg.Slug, arg.ExcludedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAdminEntryByID = `-- name: GetAdminEntryByID :one
SELECT
    e.id,
    e.revision,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.world,
    e.kind,
    e.title,
    e.slug,
    e.summary,
    e.content_md,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c
    ON c.id = e.category_id
   AND c.world = e.world
WHERE e.id = $1
  AND e.deleted_at IS NULL
`

type GetAdminEntryByIDRow struct {
	ID           int64
	Revision     int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	World        string
	Kind         string
	Title        string
	Slug         string
	Summary      *string
	ContentMd    string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetAdminEntryByID(ctx context.Context, id int64) (GetAdminEntryByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminEntryByID, id)
	var i GetAdminEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.AuthorID,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.World,
		&i.Kind,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkEntryBySlug = `-- name: GetLinkEntryBySlug :one
SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.world,
    e.kind,
    e.title,
    e.slug,
    e.summary,
    e.content_md,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c
    ON c.id = e.category_id
   AND c.world = e.world
WHERE e.world = $1
  AND e.slug = $2
  AND e.deleted_at IS NULL
  AND e.status = 'published'
  AND e.visibility IN ('public', 'unlisted')
`

type GetLinkEntryBySlugParams struct {
	World string
	Slug  string
}

type GetLinkEntryBySlugRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	World        string
	Kind         string
	Title        string
	Slug         string
	Summary      *string
	ContentMd    string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetLinkEntryBySlug(ctx context.Context, arg GetLinkEntryBySlugParams) (GetLinkEntryBySlugRow, error) {
	row := q.db.QueryRow(ctx, getLinkEntryBySlug, arg.World, arg.Slug)
	var i GetLinkEntryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.World,
		&i.Kind,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicEntryBySlug = `-- name: GetPublicEntryBySlug :one
SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.world,
    e.kind,
    e.title,
    e.slug,
    e.summary,
    e.content_md,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c
    ON c.id = e.category_id
   AND c.world = e.world
WHERE e.world = $1
  AND e.slug = $2
  AND e.deleted_at IS NULL
  AND e.status = 'published'
  AND e.visibility = 'public'
`

type GetPublicEntryBySlugParams struct {
	World string
	Slug  string
}

type GetPublicEntryBySlugRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	World        string
	Kind         string
	Title        string
	Slug         string
	Summary      *string
	ContentMd    string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetPublicEntryBySlug(ctx context.Context, arg GetPublicEntryBySlugParams) (GetPublicEntryBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicEntryBySlug, arg.World, arg.Slug)
	var i GetPublicEntryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategorySlug,
		&i.World,
		&i.Kind,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminEntries = `-- name: ListAdminEntries :many
SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.world,
    e.kind,
    e.title,
    e.slug,
    e.summary,
    CASE WHEN e.world = 'saying' THEN e.content_md ELSE ''::text END AS content_md,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c
    ON c.id = e.category_id
   AND c.world = e.world
WHERE e.deleted_at IS NULL
  AND ($1::varchar IS NULL OR e.world = $1::varchar)
  AND ($2::bigint IS NULL OR e.category_id = $2::bigint)
  AND ($3::varchar IS NULL OR e.status = $3::varchar)
  AND (
    $4::text IS NULL
    OR e.title ILIKE '%' || $4::text || '%'
    OR e.slug ILIKE '%' || $4::text || '%'
    OR COALESCE(e.summary, '') ILIKE '%' || $4::text || '%'
  )
ORDER BY e.updated_at DESC, e.id DESC
LIMIT $6 OFFSET $5
`

type ListAdminEntriesParams struct {
	World      *string
	CategoryID *int64
	Status     *string
	Search     *string
	Offset     int32
	Limit      int32
}

type ListAdminEntriesRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	World        string
	Kind         string
	Title        string
	Slug         string
	Summary      *string
	ContentMd    string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListAdminEntries(ctx context.Context, arg ListAdminEntriesParams) ([]ListAdminEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAdminEntries,
		arg.World,
		arg.CategoryID,
		arg.Status,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminEntriesRow{}
	for rows.Next() {
		var i ListAdminEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.World,
			&i.Kind,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.ContentMd,
			&i.CoverUrl,
			&i.Status,
			&i.Visibility,
			&i.Meta,
			&i.WordCount,
			&i.HappenedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicEntries = `-- name: ListPublicEntries :many
SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.world,
    e.kind,
    e.title,
    e.slug,
    e.summary,
    e.content_md,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c
    ON c.id = e.category_id
   AND c.world = e.world
WHERE e.world = $1
  AND e.deleted_at IS NULL
  AND e.status = 'published'
  AND e.visibility = 'public'
  AND ($2::bigint IS NULL
       OR e.category_id = $2::bigint)
ORDER BY e.display_order DESC, COALESCE(e.happened_at, e.published_at) DESC, e.id DESC
LIMIT $4 OFFSET $3
`

type ListPublicEntriesParams struct {
	World      string
	CategoryID *int64
	Offset     int32
	Limit      int32
}

type ListPublicEntriesRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	World        string
	Kind         string
	Title        string
	Slug         string
	Summary      *string
	ContentMd    string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListPublicEntries(ctx context.Context, arg ListPublicEntriesParams) ([]ListPublicEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPublicEntries,
		arg.World,
		arg.CategoryID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicEntriesRow{}
	for rows.Next() {
		var i ListPublicEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.World,
			&i.Kind,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.ContentMd,
			&i.CoverUrl,
			&i.Status,
			&i.Visibility,
			&i.Meta,
			&i.WordCount,
			&i.HappenedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEntriesForOrdering = `-- name: ListPublishedEntriesForOrdering :many
SELECT
    e.id,
    e.author_id,
    e.category_id,
    c.name AS category_name,
    c.slug AS category_slug,
    e.world,
    e.kind,
    e.title,
    e.slug,
    e.summary,
    CASE WHEN e.world = 'saying' THEN e.content_md ELSE ''::text END AS content_md,
    e.cover_url,
    e.status,
    e.visibility,
    e.meta,
    e.word_count,
    e.happened_at,
    e.published_at,
    e.created_at,
    e.updated_at
FROM entries e
LEFT JOIN categories c
    ON c.id = e.category_id
   AND c.world = e.world
WHERE e.world = $1
  AND e.deleted_at IS NULL
  AND e.status = 'published'
ORDER BY e.display_order DESC, e.id DESC
`

type ListPublishedEntriesForOrderingRow struct {
	ID           int64
	AuthorID     int64
	CategoryID   *int64
	CategoryName *string
	CategorySlug *string
	World        string
	Kind         string
	Title        string
	Slug         string
	Summary      *string
	ContentMd    string
	CoverUrl     *string
	Status       string
	Visibility   string
	Meta         json.RawMessage
	WordCount    int32
	HappenedAt   *time.Time
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListPublishedEntriesForOrdering(ctx context.Context, world string) ([]ListPublishedEntriesForOrderingRow, error) {
	rows, err := q.db.Query(ctx, listPublishedEntriesForOrdering, world)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedEntriesForOrderingRow{}
	for rows.Next() {
		var i ListPublishedEntriesForOrderingRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategorySlug,
			&i.World,
			&i.Kind,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.ContentMd,
			&i.CoverUrl,
			&i.Status,
			&i.Visibility,
			&i.Meta,
			&i.WordCount,
			&i.HappenedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishEntry = `-- name: PublishEntry :one
UPDATE entries
SET
    revision = revision + 1,
    status = 'published',
    published_at = COALESCE(published_at, $1),
    display_order = CASE
      WHEN status <> 'published' THEN (
        SELECT COALESCE(MAX(other.display_order), 0) + 1
        FROM entries other
        WHERE other.world = entries.world
          AND other.deleted_at IS NULL
          AND other.status = 'published'
      )
      ELSE display_order
    END
WHERE entries.id = $2
  AND entries.revision = $3
  AND entries.deleted_at IS NULL
RETURNING
    id,
    revision,
    author_id,
    category_id,
    world,
    kind,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type PublishEntryParams struct {
	PublishedAt      *time.Time
	ID               int64
	ExpectedRevision int64
}

type PublishEntryRow struct {
	ID          int64
	Revision    int64
	AuthorID    int64
	CategoryID  *int64
	World       string
	Kind        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) PublishEntry(ctx context.Context, arg PublishEntryParams) (PublishEntryRow, error) {
	row := q.db.QueryRow(ctx, publishEntry, arg.PublishedAt, arg.ID, arg.ExpectedRevision)
	var i PublishEntryRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.AuthorID,
		&i.CategoryID,
		&i.World,
		&i.Kind,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteEntry = `-- name: SoftDeleteEntry :one
UPDATE entries
SET deleted_at = $1
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteEntryParams struct {
	DeletedAt *time.Time
	ID        int64
}

func (q *Queries) SoftDeleteEntry(ctx context.Context, arg SoftDeleteEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteEntry, arg.DeletedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const unpublishEntry = `-- name: UnpublishEntry :one
UPDATE entries
SET
    revision = revision + 1,
    status = 'draft'
WHERE id = $1
  AND revision = $2
  AND deleted_at IS NULL
RETURNING
    id,
    revision,
    author_id,
    category_id,
    world,
    kind,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type UnpublishEntryParams struct {
	ID               int64
	ExpectedRevision int64
}

type UnpublishEntryRow struct {
	ID          int64
	Revision    int64
	AuthorID    int64
	CategoryID  *int64
	World       string
	Kind        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UnpublishEntry(ctx context.Context, arg UnpublishEntryParams) (UnpublishEntryRow, error) {
	row := q.db.QueryRow(ctx, unpublishEntry, arg.ID, arg.ExpectedRevision)
	var i UnpublishEntryRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.AuthorID,
		&i.CategoryID,
		&i.World,
		&i.Kind,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET
    revision = revision + 1,
    title = CASE WHEN $1::boolean
                 THEN $2::varchar ELSE title END,
    slug = CASE WHEN $3::boolean
                THEN $4::varchar ELSE slug END,
    summary = CASE WHEN $5::boolean
                   THEN $6::text ELSE summary END,
    content_md = CASE WHEN $7::boolean
                      THEN $8::text ELSE content_md END,
    word_count = CASE WHEN $7::boolean
                      THEN $9::int ELSE word_count END,
    cover_url = CASE WHEN $10::boolean
                     THEN $11::text ELSE cover_url END,
    visibility = CASE WHEN $12::boolean
                      THEN $13::varchar ELSE visibility END,
    meta = CASE WHEN $14::boolean
                THEN $15::jsonb ELSE meta END,
    happened_at = CASE WHEN $16::boolean
                       THEN $17::timestamptz ELSE happened_at END,
    category_id = CASE WHEN $18::boolean
                       THEN $19::bigint ELSE category_id END
WHERE id = $20
  AND revision = $21
  AND deleted_at IS NULL
RETURNING
    id,
    revision,
    author_id,
    category_id,
    world,
    kind,
    title,
    slug,
    summary,
    content_md,
    cover_url,
    status,
    visibility,
    meta,
    word_count,
    happened_at,
    published_at,
    created_at,
    updated_at
`

type UpdateEntryParams struct {
	SetTitle         bool
	Title            string
	SetSlug          bool
	Slug             string
	SetSummary       bool
	Summary          *string
	SetContentMd     bool
	ContentMd        string
	WordCount        int32
	SetCoverUrl      bool
	CoverUrl         *string
	SetVisibility    bool
	Visibility       string
	SetMeta          bool
	Meta             json.RawMessage
	SetHappenedAt    bool
	HappenedAt       *time.Time
	SetCategoryID    bool
	CategoryID       *int64
	ID               int64
	ExpectedRevision int64
}

type UpdateEntryRow struct {
	ID          int64
	Revision    int64
	AuthorID    int64
	CategoryID  *int64
	World       string
	Kind        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (UpdateEntryRow, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.SetTitle,
		arg.Title,
		arg.SetSlug,
		arg.Slug,
		arg.SetSummary,
		arg.Summary,
		arg.SetContentMd,
		arg.ContentMd,
		arg.WordCount,
		arg.SetCoverUrl,
		arg.CoverUrl,
		arg.SetVisibility,
		arg.Visibility,
		arg.SetMeta,
		arg.Meta,
		arg.SetHappenedAt,
		arg.HappenedAt,
		arg.SetCategoryID,
		arg.CategoryID,
		arg.ID,
		arg.ExpectedRevision,
	)
	var i UpdateEntryRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.AuthorID,
		&i.CategoryID,
		&i.World,
		&i.Kind,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.ContentMd,
		&i.CoverUrl,
		&i.Status,
		&i.Visibility,
		&i.Meta,
		&i.WordCount,
		&i.HappenedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
