// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlcgen

import (
	"context"
	"time"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (author_id, object_key, url, mime_type, byte_size)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author_id, object_key, url, mime_type, byte_size, created_at
`

type CreateMediaParams struct {
	AuthorID  int64
	ObjectKey string
	Url       string
	MimeType  string
	ByteSize  int64
}

type CreateMediaRow struct {
	ID        int64
	AuthorID  int64
	ObjectKey string
	Url       string
	MimeType  string
	ByteSize  int64
	CreatedAt time.Time
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (CreateMediaRow, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.AuthorID,
		arg.ObjectKey,
		arg.Url,
		arg.MimeType,
		arg.ByteSize,
	)
	var i CreateMediaRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ObjectKey,
		&i.Url,
		&i.MimeType,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, author_id, object_key, url, mime_type, byte_size, created_at
FROM media WHERE id = $1
`

type GetMediaByIDRow struct {
	ID        int64
	AuthorID  int64
	ObjectKey string
	Url       string
	MimeType  string
	ByteSize  int64
	CreatedAt time.Time
}

func (q *Queries) GetMediaByID(ctx context.Context, id int64) (GetMediaByIDRow, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i GetMediaByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ObjectKey,
		&i.Url,
		&i.MimeType,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const listMediaForEntry = `-- name: ListMediaForEntry :many
SELECT m.id, m.author_id, m.object_key, m.url, m.mime_type, m.byte_size, m.created_at
FROM media m
JOIN entry_media em ON em.media_id = m.id
WHERE em.entry_id = $1
ORDER BY em.created_at, m.id
`

type ListMediaForEntryRow struct {
	ID        int64
	AuthorID  int64
	ObjectKey string
	Url       string
	MimeType  string
	ByteSize  int64
	CreatedAt time.Time
}

func (q *Queries) ListMediaForEntry(ctx context.Context, entryID int64) ([]ListMediaForEntryRow, error) {
	rows, err := q.db.Query(ctx, listMediaForEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaForEntryRow{}
	for rows.Next() {
		var i ListMediaForEntryRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ObjectKey,
			&i.Url,
			&i.MimeType,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
