// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlcgen

import (
	"context"
	"time"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (author_id, object_key, mime_type, byte_size)
VALUES ($1, $2, $3, $4)
RETURNING id, author_id, object_key, mime_type, byte_size, created_at
`

type CreateMediaParams struct {
	AuthorID  int64
	ObjectKey string
	MimeType  string
	ByteSize  int64
}

type CreateMediaRow struct {
	ID        int64
	AuthorID  int64
	ObjectKey string
	MimeType  string
	ByteSize  int64
	CreatedAt time.Time
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (CreateMediaRow, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.AuthorID,
		arg.ObjectKey,
		arg.MimeType,
		arg.ByteSize,
	)
	var i CreateMediaRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, author_id, object_key, mime_type, byte_size, created_at
FROM media WHERE id = $1
`

type GetMediaByIDRow struct {
	ID        int64
	AuthorID  int64
	ObjectKey string
	MimeType  string
	ByteSize  int64
	CreatedAt time.Time
}

func (q *Queries) GetMediaByID(ctx context.Context, id int64) (GetMediaByIDRow, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i GetMediaByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.CreatedAt,
	)
	return i, err
}
