// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"encoding/json"
	"net/netip"
	"time"
)

type Category struct {
	ID          int64
	Name        string
	Slug        string
	Description *string
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	World       string
}

type Entry struct {
	ID          int64
	AuthorID    int64
	Type        string
	Title       string
	Slug        string
	Summary     *string
	ContentMd   string
	CoverUrl    *string
	Status      string
	Visibility  string
	Meta        json.RawMessage
	WordCount   int32
	HappenedAt  *time.Time
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	CategoryID  *int64
	Revision    int64
	World       string
	Kind        string
}

type EntryTag struct {
	EntryID   int64
	TagID     int64
	CreatedAt time.Time
}

type Session struct {
	ID                int64
	UserID            int64
	TokenHash         []byte
	ExpiresAt         time.Time
	CreatedAt         time.Time
	UserAgent         *string
	Ip                *netip.Addr
	AbsoluteExpiresAt time.Time
}

type SiteSetting struct {
	ID           int16
	DefaultTheme string
	Revision     int64
	UpdatedAt    time.Time
}

type SiteWorld struct {
	World       string
	Status      string
	NavLabel    string
	SortOrder   int32
	DefaultView string
	Revision    int64
	UpdatedAt   time.Time
}

type Tag struct {
	ID        int64
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	Role         string
	DisplayName  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
