// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	ArchiveEntry(ctx context.Context, arg ArchiveEntryParams) (ArchiveEntryRow, error)
	CategorySlugExists(ctx context.Context, arg CategorySlugExistsParams) (bool, error)
	CategorySlugExistsExcluding(ctx context.Context, arg CategorySlugExistsExcludingParams) (bool, error)
	CountAdminEntries(ctx context.Context, arg CountAdminEntriesParams) (int64, error)
	CountPublicEntries(ctx context.Context, arg CountPublicEntriesParams) (int64, error)
	CountPublicEntriesByTag(ctx context.Context, slug string) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (CreateEntryRow, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (CreateMediaRow, error)
	// token_hash is supplied by the caller, already hashed. The plaintext token
	// never reaches the database.
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	// Queries for the owner account and its sessions.
	//
	// These return database facts and nothing more. Whether a session has expired
	// is a decision, so it is not encoded here: GetSessionByHash returns an expired
	// row and lets the service layer rule on it. A SQL-level expiry filter would
	// make "expired" and "no such session" indistinguishable to the caller.
	// password_hash is written but not returned. A hash has no use above the
	// repository except during a login comparison, which GetUserByUsername serves.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DashboardMetrics(ctx context.Context) (DashboardMetricsRow, error)
	DeleteCategory(ctx context.Context, id int64) (int64, error)
	// Periodic cleanup, driven by a CLI command. Returns the number of rows removed
	// so the command can report it.
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	// Logout. Deleting a missing row is not an error here; the caller's goal is
	// that the session no longer exists, and it does not.
	DeleteSession(ctx context.Context, id int64) error
	// Logout. The request carries only the cookie, so deleting by hash ends the
	// session in one round trip instead of a lookup followed by a delete by id.
	// DeleteSession stays for callers that already hold the id.
	DeleteSessionByHash(ctx context.Context, tokenHash []byte) error
	DeleteTag(ctx context.Context, id int64) (int64, error)
	EntrySlugExists(ctx context.Context, arg EntrySlugExistsParams) (bool, error)
	EntrySlugExistsExcluding(ctx context.Context, arg EntrySlugExistsExcludingParams) (bool, error)
	GetAdminEntryByID(ctx context.Context, id int64) (GetAdminEntryByIDRow, error)
	GetCategoryByID(ctx context.Context, id int64) (GetCategoryByIDRow, error)
	GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (GetCategoryBySlugRow, error)
	GetLinkEntryBySlug(ctx context.Context, arg GetLinkEntryBySlugParams) (GetLinkEntryBySlugRow, error)
	GetMediaByID(ctx context.Context, id int64) (GetMediaByIDRow, error)
	GetPublicEntryBySlug(ctx context.Context, arg GetPublicEntryBySlugParams) (GetPublicEntryBySlugRow, error)
	// The authentication lookup. One round trip returns the session and its user,
	// because this runs on every protected request and a second query would double
	// that cost.
	//
	// Deliberately no "AND expires_at > now()". The row comes back whatever its
	// expiry, and the service decides. That keeps two different outcomes apart:
	// an unknown token and a known but expired one.
	GetSessionByHash(ctx context.Context, tokenHash []byte) (GetSessionByHashRow, error)
	GetSiteSettings(ctx context.Context) (GetSiteSettingsRow, error)
	GetTagByID(ctx context.Context, id int64) (Tag, error)
	GetTagBySlug(ctx context.Context, slug string) (Tag, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	// The login lookup, and the only query that exposes password_hash.
	//
	// No lower() on either side: username is citext, so the comparison is already
	// case-insensitive. Wrapping the column in lower() would also make the query
	// unable to use the unique index.
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWorld(ctx context.Context, world string) (SiteWorld, error)
	ListAdminEntries(ctx context.Context, arg ListAdminEntriesParams) ([]ListAdminEntriesRow, error)
	ListAllWorlds(ctx context.Context) ([]SiteWorld, error)
	ListCategories(ctx context.Context, world string) ([]ListCategoriesRow, error)
	ListCategoriesWithCounts(ctx context.Context, world string) ([]ListCategoriesWithCountsRow, error)
	ListMediaForEntry(ctx context.Context, entryID int64) ([]ListMediaForEntryRow, error)
	ListOpenWorlds(ctx context.Context) ([]SiteWorld, error)
	ListPublicEntries(ctx context.Context, arg ListPublicEntriesParams) ([]ListPublicEntriesRow, error)
	ListPublicEntriesByTag(ctx context.Context, arg ListPublicEntriesByTagParams) ([]ListPublicEntriesByTagRow, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error)
	ListTagsByEntryID(ctx context.Context, entryID int64) ([]Tag, error)
	PublishEntry(ctx context.Context, arg PublishEntryParams) (PublishEntryRow, error)
	SoftDeleteEntry(ctx context.Context, arg SoftDeleteEntryParams) (int64, error)
	TagNameExists(ctx context.Context, name string) (bool, error)
	TagSlugExists(ctx context.Context, slug string) (bool, error)
	// Sliding renewal. The service calls this only when a session is past the
	// halfway point of its lifetime, so an active session is not one write per
	// request.
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UnpublishEntry(ctx context.Context, arg UnpublishEntryParams) (UnpublishEntryRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (UpdateCategoryRow, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (UpdateEntryRow, error)
	UpdateSiteTheme(ctx context.Context, arg UpdateSiteThemeParams) (UpdateSiteThemeRow, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateWorld(ctx context.Context, arg UpdateWorldParams) (SiteWorld, error)
}

var _ Querier = (*Queries)(nil)
