// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site.sql

package sqlcgen

import (
	"context"
	"time"
)

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT default_theme, revision, updated_at
FROM site_settings
WHERE id = 1
`

type GetSiteSettingsRow struct {
	DefaultTheme string
	Revision     int64
	UpdatedAt    time.Time
}

func (q *Queries) GetSiteSettings(ctx context.Context) (GetSiteSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSiteSettings)
	var i GetSiteSettingsRow
	err := row.Scan(&i.DefaultTheme, &i.Revision, &i.UpdatedAt)
	return i, err
}

const updateSiteTheme = `-- name: UpdateSiteTheme :one
UPDATE site_settings
SET default_theme = $1,
    revision = revision + 1
WHERE id = 1
  AND revision = $2
RETURNING default_theme, revision, updated_at
`

type UpdateSiteThemeParams struct {
	DefaultTheme     string
	ExpectedRevision int64
}

type UpdateSiteThemeRow struct {
	DefaultTheme string
	Revision     int64
	UpdatedAt    time.Time
}

func (q *Queries) UpdateSiteTheme(ctx context.Context, arg UpdateSiteThemeParams) (UpdateSiteThemeRow, error) {
	row := q.db.QueryRow(ctx, updateSiteTheme, arg.DefaultTheme, arg.ExpectedRevision)
	var i UpdateSiteThemeRow
	err := row.Scan(&i.DefaultTheme, &i.Revision, &i.UpdatedAt)
	return i, err
}
