// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package sqlcgen

import (
	"context"
	"time"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
    name,
    slug
) VALUES (
    $1, $2
)
RETURNING
    id,
    name,
    slug,
    created_at,
    updated_at
`

type CreateTagParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :one
DELETE FROM tags
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteTag, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT
    id,
    name,
    slug,
    created_at,
    updated_at
FROM tags
WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT
    id,
    name,
    slug,
    created_at,
    updated_at
FROM tags
WHERE slug = $1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT
    t.id,
    t.name,
    t.slug,
    t.created_at,
    t.updated_at,
    count(e.id) AS usage_count
FROM tags t
LEFT JOIN entry_tags et
    ON et.tag_id = t.id
LEFT JOIN entries e
    ON e.id = et.entry_id
   AND e.deleted_at IS NULL
WHERE $1 = ''
   OR lower(t.name) LIKE '%' || lower($1) || '%'
   OR lower(t.slug) LIKE '%' || lower($1) || '%'
GROUP BY t.id
ORDER BY
    CASE
        WHEN $1 = '' THEN 1
        WHEN lower(t.name) LIKE lower($1) || '%'
          OR lower(t.slug) LIKE lower($1) || '%' THEN 0
        ELSE 1
    END,
    lower(t.name),
    t.id
LIMIT $2
`

type ListTagsParams struct {
	Query interface{}
	Limit int32
}

type ListTagsRow struct {
	ID         int64
	Name       string
	Slug       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UsageCount int64
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagNameExists = `-- name: TagNameExists :one
SELECT EXISTS (
    SELECT 1
    FROM tags
    WHERE name = $1
)
`

func (q *Queries) TagNameExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, tagNameExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tagSlugExists = `-- name: TagSlugExists :one
SELECT EXISTS (
    SELECT 1
    FROM tags
    WHERE slug = $1
)
`

func (q *Queries) TagSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, tagSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET
    name = CASE WHEN $1::boolean
                THEN $2::citext ELSE name END,
    slug = CASE WHEN $3::boolean
                THEN $4::varchar ELSE slug END
WHERE id = $5
RETURNING
    id,
    name,
    slug,
    created_at,
    updated_at
`

type UpdateTagParams struct {
	SetName bool
	Name    string
	SetSlug bool
	Slug    string
	ID      int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.SetName,
		arg.Name,
		arg.SetSlug,
		arg.Slug,
		arg.ID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
