// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: world.sql

package sqlcgen

import (
	"context"
)

const getWorld = `-- name: GetWorld :one
SELECT world, status, nav_label, sort_order, default_view, revision, updated_at
FROM site_worlds
WHERE world = $1
`

func (q *Queries) GetWorld(ctx context.Context, world string) (SiteWorld, error) {
	row := q.db.QueryRow(ctx, getWorld, world)
	var i SiteWorld
	err := row.Scan(
		&i.World,
		&i.Status,
		&i.NavLabel,
		&i.SortOrder,
		&i.DefaultView,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllWorlds = `-- name: ListAllWorlds :many
SELECT world, status, nav_label, sort_order, default_view, revision, updated_at
FROM site_worlds
ORDER BY sort_order, world
`

func (q *Queries) ListAllWorlds(ctx context.Context) ([]SiteWorld, error) {
	rows, err := q.db.Query(ctx, listAllWorlds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteWorld{}
	for rows.Next() {
		var i SiteWorld
		if err := rows.Scan(
			&i.World,
			&i.Status,
			&i.NavLabel,
			&i.SortOrder,
			&i.DefaultView,
			&i.Revision,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenWorlds = `-- name: ListOpenWorlds :many
SELECT world, status, nav_label, sort_order, default_view, revision, updated_at
FROM site_worlds
WHERE status = 'open'
ORDER BY sort_order, world
`

func (q *Queries) ListOpenWorlds(ctx context.Context) ([]SiteWorld, error) {
	rows, err := q.db.Query(ctx, listOpenWorlds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteWorld{}
	for rows.Next() {
		var i SiteWorld
		if err := rows.Scan(
			&i.World,
			&i.Status,
			&i.NavLabel,
			&i.SortOrder,
			&i.DefaultView,
			&i.Revision,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorld = `-- name: UpdateWorld :one
UPDATE site_worlds
SET
  status = CASE
    WHEN $1::bool THEN $2
    ELSE status
  END,
  nav_label = CASE
    WHEN $3::bool THEN $4
    ELSE nav_label
  END,
  default_view = CASE
    WHEN $5::bool THEN $6
    ELSE default_view
  END,
  revision = revision + 1
WHERE world = $7
  AND revision = $8
RETURNING world, status, nav_label, sort_order, default_view, revision, updated_at
`

type UpdateWorldParams struct {
	SetStatus        bool
	Status           string
	SetNavLabel      bool
	NavLabel         string
	SetDefaultView   bool
	DefaultView      string
	World            string
	ExpectedRevision int64
}

func (q *Queries) UpdateWorld(ctx context.Context, arg UpdateWorldParams) (SiteWorld, error) {
	row := q.db.QueryRow(ctx, updateWorld,
		arg.SetStatus,
		arg.Status,
		arg.SetNavLabel,
		arg.NavLabel,
		arg.SetDefaultView,
		arg.DefaultView,
		arg.World,
		arg.ExpectedRevision,
	)
	var i SiteWorld
	err := row.Scan(
		&i.World,
		&i.Status,
		&i.NavLabel,
		&i.SortOrder,
		&i.DefaultView,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}
